version: '3.10'

services:
  face_recognition:
    build:
      context: .
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1